### ISSUE TITLE
FILE类型字段报错

### ISSUE THREAD

**Issue by missy0u** [leancloud/leancloud-graphql#4]
```
Unhandled Rejection at: Promise  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   Error: Blog.image field type must be Output Type but got: undefined.
       at invariant (/Users/neil/Desktop/project/tangirl/node_modules/graphql/jsutils/invariant.js:19:11)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:326:29
       at Array.forEach (native)
       at defineFieldMap (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:318:14)
       at GraphQLObjectType.getFields (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:276:44)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:207:27
       at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
       at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
       at Array.forEach (native)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
       at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
       at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
       at Array.forEach (native)
       at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
       at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
       at Array.reduce (native)
       at new GraphQLSchema (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:95:34)
       at request.then.cloudSchemas (/Users/neil/Desktop/project/tangirl/node_modules/leancloud-graphql/schema.js:189:12)
       at tryCatcher (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/promise.js:510:31),
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _cancellationParent: 
   Promise {
     _bitField: 16777216,
     _fulfillmentHandler0: 
      Error: Blog.image field type must be Output Type but got: undefined.
          at invariant (/Users/neil/Desktop/project/tangirl/node_modules/graphql/jsutils/invariant.js:19:11)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:326:29
          at Array.forEach (native)
          at defineFieldMap (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:318:14)
          at GraphQLObjectType.getFields (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:276:44)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:207:27
          at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
          at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
          at Array.forEach (native)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
          at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
          at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
          at Array.forEach (native)
          at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
          at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
          at Array.reduce (native)
          at new GraphQLSchema (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:95:34)
          at request.then.cloudSchemas (/Users/neil/Desktop/project/tangirl/node_modules/leancloud-graphql/schema.js:189:12)
          at tryCatcher (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/util.js:16:23)
          at Promise._settlePromiseFromHandler (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/promise.js:510:31),
     _rejectionHandler0: undefined,
     _promise0: undefined,
     _receiver0: undefined,
     _cancellationParent: undefined,
     _branchesRemainingToCancel: 1,
     _onCancelField: undefined } }  reason:  Error: Blog.image field type must be Output Type but got: undefined.
    at invariant (/Users/neil/Desktop/project/tangirl/node_modules/graphql/jsutils/invariant.js:19:11)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:326:29
    at Array.forEach (native)
    at defineFieldMap (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:318:14)
    at GraphQLObjectType.getFields (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/definition.js:276:44)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
    at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
    at Array.forEach (native)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
    at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
    at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:187:12)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:217:22
    at Array.forEach (native)
    at /Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:208:29
    at typeMapReducer (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/neil/Desktop/project/tangirl/node_modules/graphql/type/schema.js:95:34)
    at request.then.cloudSchemas (/Users/neil/Desktop/project/tangirl/node_modules/leancloud-graphql/schema.js:189:12)
    at tryCatcher (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/neil/Desktop/project/tangirl/node_modules/bluebird/js/release/promise.js:510:31)
```

**Comment by jysperm** [comment]
我发布了 0.3.0 这个版本解决这个问题，可以试一下
